apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  description: |
    Task to clone a GitHub repo and run Python unit tests using nose.
  params:
    - name: repo-url
      type: string
      description: The URL of the GitHub repository to test
  steps:
    - name: clone-and-test
      image: python:3.9
      script: |
        #!/bin/sh
        echo "Installing git..."
        apt-get update && apt-get install -y git
        echo "Cloning repository..."
        git clone $(params.repo-url) /workspace/src
        cd /workspace/src
        echo "Installing dependencies..."
        pip install -r requirements.txt || true
        pip install nose
        echo "Running nose tests..."
        nosetests

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: |
    A simple task to clean up the workspace directory after execution.
  steps:
    - name: cleanup-workspace
      image: alpine:3.14
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/*
